### ISSUE TITLE
How to set the transient mark mode of emacs?

### ISSUE THREAD

**Issue by sxqsfun** [rvaiya/keyd#712]
I want to set the global shortcut to emacs, but I don't know how to configure Ctrl + Space to Mark. 
(If possible, I hope some emacser can share your configuration. Thank you very much!)

**Comment by appetrosyan** [comment]
Can you explain this in a bit more detail. An example can help quite a bit

**Comment by sxqsfun** [comment]
ctrl + space sets a mark, and then use the arrow keys to select text.It is similar to the function of selecting text with the left mouse button.(Macos has this shortcut key by default)

**Comment by rvaiya** [comment]
If I understand you correctly, you can just do something like this


```
[layer]

x = toggle(shift)
```

with the obvious caveats.

**Comment by sxqsfun** [comment]
Thank you very much for your time. Maybe I didn't describe my needs clearly, I don't think it's a keymap, I think this is a new feature.
I see [xremap](https://github.com/xremap/xremap?tab=readme-ov-file#features)  has support for this feature.
Its configuration is as follows
```
keymap:
  - name: Emacs
    application:
      not: [Emacs]
    remap:
      # Mark
      C-space: { set_mark: true }
      # Cursor
      C-b: { with_mark: left }
      C-f: { with_mark: right }
      C-p: { with_mark: up }
      C-n: { with_mark: down }
```
C-space to enter mark mode, C-b/C-f/C-p/C-n to select text.
