### ISSUE TITLE
Why does `capslock = home; alt+capslock = end` not bind `end`?

### ISSUE THREAD

**Issue by fpdotmonkey** [rvaiya/keyd#877]
This isn't really a "problem" since I've solved it, but it's unintuitive to me so I'm just seeking knowledge.  Under my understanding, this config should bind `home` to `capslock` and `end` to `alt+capslock`.

```toml
[ids]
*
[main]
capslock = home
alt+capslock = end
```
However, it doesn't bind end; I get `alt+home` out of `keyd monitor`.  Instead I have to do this.
```toml
[ids]
*
[main]
alt = layer(alt_capslock_is_end)
capslock = home

[alt_capslock_is_end:A]
capslock = end
```
It makes sense to me why this latter version works, but I'm just interested to know why the first shouldn't.
